package com.dichotome.klox.scanner

enum class TokenType {

    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COLON, COMMA, SEMICOLON, DOT, QUESTION, NEW_LINE,

    // One or two character tokens.
    PLUS_PLUS, MINUS_MINUS, BANG, BANG_EQUAL, EQUAL, MOD, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, MOD_EQUAL, HAT, HAT_EQUAL, MINUS, PLUS, SLASH, STAR,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords.
    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR, RETURN, SUPER, THIS, TRUE, VAR, WHILE, BREAK, CONTINUE,

    EOF;
}